"""
Generate small sample files for conversion testing.
Outputs to `backend/tests/samples/`.
"""

from pathlib import Path

SAMPLES_DIR = Path(__file__).parent / "samples"
SAMPLES_DIR.mkdir(parents=True, exist_ok=True)


def make_txt():
    (SAMPLES_DIR / "sample.txt").write_text(
        "Hello ConvertEasy!\n这是一个测试文本。\n", encoding="utf-8"
    )


def make_html():
    (SAMPLES_DIR / "sample.html").write_text(
        """<!doctype html><html><head><meta charset='utf-8'><title>Sample</title></head>
        <body><h1>ConvertEasy</h1><p>Simple HTML sample.</p></body></html>""",
        encoding="utf-8",
    )


def make_docx():
    try:
        from docx import Document
    except Exception:
        print("python-docx not installed; skip DOCX")
        return
    doc = Document()
    doc.add_heading("ConvertEasy Sample", level=1)
    doc.add_paragraph("This is a small DOCX file used for testing.")
    doc.save(SAMPLES_DIR / "sample.docx")


def make_xlsx():
    try:
        from openpyxl import Workbook
    except Exception:
        print("openpyxl not installed; skip XLSX")
        return
    wb = Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    ws["A1"] = "ConvertEasy"
    ws["B1"] = "Sample"
    ws["A2"] = 123
    ws["B2"] = 456
    wb.save(SAMPLES_DIR / "sample.xlsx")


def make_wav(duration_sec: float = 0.25, sample_rate: int = 8000):
    # Generate a tiny silent WAV using stdlib
    import wave
    import struct

    frames = int(duration_sec * sample_rate)
    with wave.open(str(SAMPLES_DIR / "sample.wav"), "w") as w:
        w.setnchannels(1)
        w.setsampwidth(2)  # 16-bit PCM
        w.setframerate(sample_rate)
        silence = struct.pack("<h", 0)
        for _ in range(frames):
            w.writeframes(silence)


def make_mp3():
    """Generate tiny MP3 using FFmpeg if available, else skip"""
    import subprocess
    import shutil

    if not shutil.which("ffmpeg"):
        print("FFmpeg not found; skip MP3 generation")
        return

    # Generate from WAV
    wav_path = SAMPLES_DIR / "sample.wav"
    if not wav_path.exists():
        make_wav()

    mp3_path = SAMPLES_DIR / "sample.mp3"
    try:
        subprocess.run(
            ["ffmpeg", "-y", "-i", str(wav_path), "-b:a", "64k", str(mp3_path)],
            check=True,
            capture_output=True,
        )
        print(f"✓ Generated {mp3_path}")
    except subprocess.CalledProcessError as e:
        print(f"✗ Failed to generate MP3: {e}")


def make_pdf():
    """Generate a simple PDF using reportlab if available"""
    try:
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import A4
    except ImportError:
        print("reportlab not installed; skip PDF generation")
        return

    pdf_path = SAMPLES_DIR / "sample.pdf"
    c = canvas.Canvas(str(pdf_path), pagesize=A4)
    c.setFont("Helvetica", 16)
    c.drawString(100, 750, "ConvertEasy Sample PDF")
    c.setFont("Helvetica", 12)
    c.drawString(100, 720, "This is a test PDF file for conversion.")
    c.drawString(100, 700, "Generated by gen_samples.py")
    c.save()
    print(f"✓ Generated {pdf_path}")


def make_images():
    """Generate sample JPG and PNG images using Pillow"""
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        print("Pillow not installed; skip Images")
        return

    # Create a simple image
    img = Image.new("RGB", (100, 100), color="red")
    d = ImageDraw.Draw(img)
    d.text((10, 10), "Test", fill=(255, 255, 0))

    # Save as JPG
    jpg_path = SAMPLES_DIR / "sample.jpg"
    img.save(jpg_path)
    print(f"✓ Generated {jpg_path}")

    # Save as PNG
    png_path = SAMPLES_DIR / "sample.png"
    img.save(png_path)
    print(f"✓ Generated {png_path}")


def main():
    make_txt()
    make_html()
    make_docx()
    make_xlsx()
    make_wav()
    make_mp3()
    make_pdf()
    make_images()
    print(f"\nSamples written to: {SAMPLES_DIR}")


if __name__ == "__main__":
    main()
